### PR TITLE
Added timestamp support && Make compatibility with latest Joi

### LINKED ISSUE #13: Bump joi@9.0.0
Hi,

Joi released a new version two weeks ago (`9.0.0`). It might be time to update `joi-to-json-schema` dependency. I think there's gonna be incompatibilities (we ran into a few issues with model label ourselves). 

I got some time to look into it this week. Is it worth the effort?

### LINKED ISSUE #20: [Object object] instead of regex in output when using joi 10.2.2
From the README.md example, modified to include console.log:
```js
var joi = require('joi'),
    convert = require('joi-to-json-schema'),
    joiSchema = joi.object({
      'name': joi.string().required().regex(/^\w+$/),
      'description': joi.string().optional().default('no description provided'),
      'a': joi.boolean().required().default(false),
      'b': joi.alternatives().when('a', {
        is: true,
        then: joi.string().default('a is true'),
        otherwise: joi.number().default(0)
      })
    });

console.log(convert(joiSchema));
```

Expected:
```js
{ type: 'object',
  properties: 
   { name: { type: 'string', pattern: '^\\w+$' },
     description: { default: 'no description provided', type: 'string' },
     a: { type: 'boolean', default: false },
     b: { oneOf: [ { default: 'a is true', type: 'string' }, { type: 'number', default: 0 } ] } },
  additionalProperties: false,
  required: [ 'name', 'a' ] }
```

Actual:
```js
{ type: 'object',
  properties: 
   { name: { type: 'string', pattern: '[object Object]' },
     description: { default: 'no description provided', type: 'string' },
     a: { default: false, type: 'boolean' },
     b: { oneOf: [Object] } },
  additionalProperties: true,
  patterns: [],
  required: [ 'name', 'a' ] }
```

### LINKED ISSUE #27: Support `Joi.date().timestamp()` schema
Currently, `joi-to-json-schema` converts `Joi.date().timestamp()` schema to date-time formatted string type.
but actually `Joi.date().timestamp()` schema validates unix timestamp (sec based) or javascript timestamp (ms based), which is actual type is integer.

### PR DESCRIPTION
**Pull request by mooyoul**
## Summary

I've added timestamp (Joi.date().timestamp()) support and made compatibility with latest Joi, without losing backward compatibility (Joi v6.10.1 for example)

### Changes

1. fixed broken `Joi.string().regex()` support with latest Joi
2. bump joi dev dependency version
3. added  `Joi.date().timestamp()` support

### Affected Issues

Closes #13
Closes #20
Closes #27

### CODE REVIEW

**Comment by mooyoul** [comment]
Plus:

# Required action after merge

- bump package version
- publish to npm

Cheers 🍻

**Comment by mooyoul** [comment]
Currently Travis is failing, because yarn dropped old node.js runtime support.
It seems we need to update minimum node.js version

**Comment by mooyoul** [comment]
Okay, build failed again. 
at this time, yarn claims that Joi requires node version greater than or equal to Node.js v8.

I've digged further details, and found this: https://github.com/hapijs/joi/issues/1328
From Joi v13, Joi changed Node.js v8 as minimum supported node.js version, because they've changed their codebase to use default parameter assignment.

So i'm going to change our devDependency to use joi v12.

**Comment by mooyoul** [comment]
Okay, Test Passed ;)

**Comment by lightsofapollo** [comment]
Will land this later today or early tomorrow. Thanks for the updates !

**Comment by lightsofapollo** [comment]
in v3.1.0

**Comment by mooyoul** [comment]
Thanks! 😄

**Pull request merged**
