### PR TITLE
feat: support for "joi.options.presence = required"

### PR DESCRIPTION
**Pull request by simlu**

### CODE REVIEW

**Comment by simlu** [comment]
Fixes https://github.com/lightsofapollo/joi-to-json-schema/issues/48

I've also updated dev dependencies (lodash and joi) and fixed tests (very minor changes)

**Comment by simlu** [comment]
@lightsofapollo Would you mind taking a look? We'd really appreciate if this could get merged in

**Comment by simlu** [comment]
@lightsofapollo Sorry for the continuous nudging. I'm sure you're busy, but we'd really appreciate if you could take a quick look.

**Comment by lightsofapollo** [comment]
Back from vaca! Looking right now.

**Comment by lightsofapollo** [comment]
Nagging appreciated !

**Comment by lightsofapollo** [comment]
Released in `5.1.0`

**Comment by simlu** [comment]
Sweet, thank you very much!

**Pull request merged**
